baseURL = "https://miloszsynecki.github.io/"
title = "Miłosz Synecki"
theme = "hugo-theme-terminal"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true
summaryLength = 0

[pagination]
pagerSize = 6

[outputs]
home = ["HTML", "RSS"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
