[params]
contentTypeName = "notes"
showMenuItems = 4
fullWidthTheme = false
centerTheme = true
themeColor = "orange"
showLastUpdated = false
readingTime = true

[params.logo]
logoText = "Miłosz Synecki"
logoHomeLink = "/"
